Answer sheet and form
Projeto-Adocao-Caosciente/adocao-caosciente-backend pull request #22
Opened 2023-12-01 19:35 UTC by mrlFranchi

2023-12-01 19:39 UTC, Ryrden commented on app/domain/models/answerSheet.py
> +        }
Esse deve ser o novo nome. `schema_extra` está deprecated

```suggestion
    class Config:
        json_schema_extra = {
            "adopter_id": "653efb24188b172ef77d8acc",
            "form_id": "653efee7eb19804a4a56fc86",
            "score": 7,
            "answers": [1,2]
        }
```

2023-12-01 19:41 UTC, Ryrden commented on app/routes/answer_sheet_route.py
> +jwt_bearer = JWTBearer()
Adicionar um TODO para melhorar essa parte futuramente
```suggestion
# TODO: Formulário está altamente acoplado com outras classes
ong_service = OngService()
animal_service = AnimalService(ong_service)
form_service = FormService(ong_service, animal_service)
adopter_service = AdopterService()
answerService = AnswerSheetService(form_service, adopter_service)
jwt_bearer = JWTBearer()
```

2023-12-01 19:42 UTC, Ryrden commented on app/routes/answer_sheet_route.py
> +    answer_sheet: AnswerSheetModel = Body(..., example=AnswerSheetModel.Config.schema_extra)):
```suggestion
    answer_sheet: AnswerSheetModel = Body(..., example=AnswerSheetModel.Config.schema_extra)
):
```

2023-12-01 21:58 UTC, Ryrden commented on app/services/answer_sheet_service.py
> +                answerSheet.adopter_id = user_id
seria interessante checar se esse id é realmente de um adotante

2023-12-01 21:58 UTC, Ryrden commented on app/services/answer_sheet_service.py
> +                    #TODO: Tratar responses da inserção
Esse TODO já foi feito?

2023-12-01 22:00 UTC, Ryrden commented on app/services/answer_sheet_service.py
> +                return ResponseDTO(FormModel.form_helper(result),"Answer Sheet gotten successfully", http.HTTPStatus.OK)
```suggestion
                return ResponseDTO(FormModel.helper(result),"Answer Sheet gotten successfully", http.HTTPStatus.OK)
```

2023-12-01 22:05 UTC, Ryrden commented on app/services/answer_sheet_service.py
> +    # TODO: Fix when rebasing with adopter CR
O que esse TODO significa?

2023-12-01 22:09 UTC, Ryrden commented on app/services/form_service.py
> +                    #TODO; logging nao tem animal na ong
Faltou esse TODO

2023-12-01 22:09 UTC, Ryrden commented on app/services/form_service.py
> +                    # TODO: tratar rollback
Não é necessário, tudo isso é uma transaction
```suggestion
```

2023-12-01 22:10 UTC, Ryrden commented on app/services/form_service.py
> +                    return ResponseDTO(result.inserted_id,"Form created successfully", http.HTTPStatus.CREATED)
```suggestion
                    return ResponseDTO({"id": result.inserted_id},"Form created successfully", http.HTTPStatus.CREATED)
```

2023-12-01 22:13 UTC, Ryrden commented on app/services/form_service.py
> +            self.logger.info(f"id = {request_id} starting get form")
esse request_id precisa ser passado em todas as funções, ver com calma
```suggestion
        self.logger.info(f"id = {request_id} starting get form")
```

2023-12-01 22:14 UTC, Ryrden requested changes
Algumas mudanças mas ótimo trabalho, o código ficou bom pra caralho

2023-12-01 22:19 UTC, mrlFranchi commented on app/services/answer_sheet_service.py
> +                answerSheet.adopter_id = user_id
Somente um adotante deveria chegar nessa parte.. tem algum jeito de verificar isso sem fazer uma busca na coleção de adotante?

2023-12-01 22:21 UTC, mrlFranchi commented on app/services/answer_sheet_service.py
> +    # TODO: Fix when rebasing with adopter CR
tinha feito essa parte antes de ter o adotante, então precisava arrumar quando houvesse o a parte do adotante

2023-12-01 22:21 UTC, mrlFranchi commented on app/services/answer_sheet_service.py
> +                    #TODO: Tratar responses da inserção
ainda não

2023-12-01 22:22 UTC, mrlFranchi commented on app/services/form_service.py
> +                    #TODO; logging nao tem animal na ong
sim, mudei essa aprte agr na reunião com o joão

2023-12-01 22:23 UTC, mrlFranchi commented on app/services/form_service.py
> +                    # TODO: tratar rollback
então, mas o animal_service.insert_form inicia outra transação que pode ser bem sucedida. Ou acumula tudo em apenas uma transação? foi uma fuvida que tive com o joão

2023-12-01 23:06 UTC, Ryrden commented on app/services/answer_sheet_service.py
> +    # TODO: Fix when rebasing with adopter CR
Parece ok, você foi sincronizando com a main durante o desenvolvimento, sem medo de conflito

2023-12-01 23:06 UTC, Ryrden commented on app/services/answer_sheet_service.py
> +                answerSheet.adopter_id = user_id
Faz todo o sentido, isso é a task do Nicolas, autenticação de rota

2023-12-01 23:07 UTC, Ryrden commented on app/services/answer_sheet_service.py
> +                    #TODO: Tratar responses da inserção
Quando fizer me notifica

2023-12-01 23:07 UTC, Ryrden commented on app/services/form_service.py
> +                    #TODO; logging nao tem animal na ong
Sobe o commit dps

2023-12-01 23:07 UTC, Ryrden commented on app/services/form_service.py
> +                    # TODO: tratar rollback
é Exatametne igual você aprendeu em BD, é uma transação separada, se ela der pau cascateia

2023-12-01 23:09 UTC, Ryrden requested changes
bom

2023-12-03 01:27 UTC, mrlFranchi commented on app/services/answer_sheet_service.py
> +                answerSheet.adopter_id = user_id
@NicolasGoes01 posso marcar como resolvido ou deixar um TODO pra vc?

2023-12-03 02:31 UTC, mrlFranchi commented on app/services/answer_sheet_service.py
> +                    #TODO: Tratar responses da inserção
feito em partes, não tive tempo de descobrir como remover um object_ID espectifico de uma lista

2023-12-03 02:32 UTC, mrlFranchi commented on app/services/form_service.py
> +                    #TODO; logging nao tem animal na ong
feito

2023-12-03 02:34 UTC, mrlFranchi commented on app/services/form_service.py
> +                    # TODO: tratar rollback
fiz uns testes... parece que do jeito que estamos fazendo, iniciando uma transação em cada parte, se vc precisar fazer inserções em partes diferentes e uma delas da commit, a transação inteira é efetuada.. então não adianta dar abort na transação.. fiz o inicio da remoção mas ainda não consegui remover um unico object_ID de uma lista

2023-12-03 03:28 UTC, Ryrden commented on app/services/animal_service.py
> +                    return ResponseDTO({"result": result}, "Form inserted", http.HTTPStatus.OK)
Aqui basta ser result
```suggestion
                    return ResponseDTO(result, "Form inserted", http.HTTPStatus.OK)
```

2023-12-03 03:29 UTC, Ryrden commented on app/services/answer_sheet_service.py
> +                response = self.db.get_database().get_collection("adopter").find_one({"_id": ObjectId(adopter_id)})
Adicionar um TODO para melhoria futura, esse código esta acoplado
```suggestion
                # TODO: Melhorar isso com injeção de dependência no futuro
                response = self.db.get_database().get_collection("adopter").find_one({"_id": ObjectId(adopter_id)})
```

2023-12-03 03:33 UTC, Ryrden commented on app/services/form_service.py
> +                    # TODO: tratar rollback
Interessante, o ideal então é receber o contexto da transaction por endpoint, cria uma task no backlog sobre isso. 

Se a transaction ocorrer por função da service vai acontecer isso, que bom que você encontrou esse bug crítico.

Sobre a sugestão q eu dei ali no começo, isso pode ser feito com middleware, igual eu fiz a questão do request_id

2023-12-03 03:33 UTC, Ryrden commented on app/services/form_service.py
>              print(f"Error creating Forms: {e}")
```suggestion
            self.logger.error(f"id= {request_id} Error creating form {e}")
```

2023-12-03 03:34 UTC, Ryrden commented on app/services/form_service.py
>              return ResponseDTO(None, "Error Creating Form: " + str(e), http.HTTPStatus.BAD_REQUEST)
O Usuário (Cliente/Frontend) nao dseve saber detalhes de erros do backend. os logs sao para filtragem em produção, dps te mostro o deploy no render.

```suggestion
            return ResponseDTO(None, "Error Creating Form", http.HTTPStatus.BAD_REQUEST)
```

2023-12-03 03:35 UTC, Ryrden approved these changes
Parece ok, se tudo estiver funcionando, pode mergear

2023-12-03 03:36 UTC, Ryrden commented on app/services/answer_sheet_service.py
> +                    #TODO: Tratar responses da inserção
Se for detalhe, mantenha o TODO e mergeie, faça depois. amanha a task precisa estar na main para testes e integração

2023-12-03 12:11 UTC, mrlFranchi commented on app/services/animal_service.py
> +                    return ResponseDTO({"result": result}, "Form inserted", http.HTTPStatus.OK)
vdd.. tava dando erro  na serialização, achei que podia ser ai, mas aparentemente não é :v

2023-12-03 12:15 UTC, merged